#!/bin/bash

name=""
script="prepareEnvironment"
hadoop="/usr/local/hadoop"
put="${hadoop}/bin/hdfs dfs -put"

# docker run -dt zoltannz/hadoop-ubuntu:2.8.1
name=$(docker ps | grep -Eow '(\w+_\w+)$')
echo "started docker container in the background: ${name}"

# docker cp src/main/resources ${name}:${hadoop}
# docker exec -it ${name} ${put} ${hadoop}/resources/stopwords
docker exec -it ${name} ${put} ${hadoop}/resources
# docker cp target/WordCount.jar ${name}:${hadoop}
echo "copy files to ${name} OK"

#docker exec -it ${name} bash -x ${hadoop}/${script}
#echo "put files to hdfs OK"

echo "connecting to the bash ..."
docker exec -it ${name} /bin/bash